### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by pepedressingroom** [TLDRMissions/ManuscriptsJournal#14]
\db\WindingSlitherdrake.lua
--there are 2 “73854” questid, questid of item:203365 is 73857
```
        name = "Winding Slitherdrake: Hairy Throat",
        itemID = 203365,
        questID = 73857,
```

--add source for 2 pvp achievement manuscripts
\db\HighlandDrake.lua
```
        name = "Highland Drake: Embodiment of the Crimson Gladiator",
        itemID = 201792,
        questID = 72371,
        source = sources.Achievement,
        achievementID = 15957,--season1
```
\db\WindingSlitherdrake.lua
```
        name = "Winding Slitherdrake: Embodiment of the Obsidian Gladiator",
        itemID = 205865,
        questID = 75941,
        source = sources.Achievement,
        achievementID = 17740,--season2
```

The Windborne Velocidrake: Teal Scales (item:197615) will be able to be obtained when the Kalimdor Cup goes live from August 15 to 28 - 2023.
Can be bought for 30 Riders of Azeroth Badge (currency:2588) on the 10.1.5 PTR from Maztha (npc:206744) at the Rostrum of Transformation in Valdrakken.
```
    {
        name = "Windborne Velocidrake: Teal Scales",
        itemID = 197615,
        questID = 69819,
        source = sources.Vendor,
        vendorName = L["Maztha"],
        zoneID = 13862,
    },
```

--add some Zone ID in enums.lua for future use.
```
addon.Strings.Zones = {}
addon.Strings.Zones[1] = C_Map.GetAreaInfo(13645)--Ohn'ahran Plains
addon.Strings.Zones[2] = C_Map.GetAreaInfo(13644)--The Waking Shores
addon.Strings.Zones[3] = C_Map.GetAreaInfo(14022)--Zaralek Cavern
addon.Strings.Zones[4] = C_Map.GetAreaInfo(13646)--The Azure Span
addon.Strings.Zones[5] = C_Map.GetAreaInfo(13647)--Thaldraszus
addon.Strings.Zones[6] = C_Map.GetAreaInfo(13862)--Valdrakken
addon.Strings.Zones[7] = C_Map.GetAreaInfo(14433)--The Forbidden Reach
addon.Strings.Zones[8] = C_Map.GetAreaInfo(13642)--Dragon Isles
```
--I also sugguest that Dragon Riding related items could use source "Dragon Riding" in the future version.

--Since you list the souces of "Armor" 197357,197588,197099,196961, which unlocked by spell:400549 awarded by quest:70911 after renown 26 with the Accord. (the 4 manucripts exist in client but not available actually)
To keep consistent, you may hide the 4 "Armor" or show the 4 "Helm", the souces of "Helm" 197373,197600,197119,196990 which unlocked by spell:409471 awarded by quest:75742 after renown 19 with the Niffen.(also exist but not available)
\db\RenewedProtoDrake.lua
```
    {
        name = "Renewed Proto-Drake: Helm",
        itemID = 197373,
        questID = 69574,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 19,
    },
```
\db\WindborneVelocidrake.lua
```
    {
        name = "Windborne Velocidrake: Helm",
        itemID = 197600,
        questID = 69804,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 19,
    },
```
\db\HighlandDrake.lua
```
    {
        name = "Highland Drake: Helm",
        itemID = 197119,
        questID = 69320,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 19,
    },
```
\db\CliffsideWylderdrake.lua
```
    {
        name = "Cliffside Wylderdrake: Helm",
        itemID = 196990,
        questID = 69190,
        source = sources.Renown,
        renownFaction = 2564,
        renownRank = 19,
    },
```
BUT WindingSlitherdrake: Armor (203305) and WindingSlitherdrake: Helm (203326) was removed from client.

there're up to 5 items was removed from client, but item's original quest maybe still can be unlocked by other ways.
203305	WindingSlitherdrake: Armor--renown 26 with the Accord
203326	WindingSlitherdrake: Helm--renown 19 with the Niffen
203301	WindingSlitherdrake: LightBlueandCopperArmor
203302	WindingSlitherdrake: PurpleandSilverArmor
203298	WindingSlitherdrake: WhiteandGoldArmor--Dragon Isles Drakes: Gilded Armor (208200)
on the 10.1.7 ptr, there're 2 new items 208200 and 208550.
Dragon Isles Drakes: Gilded Armor (208200) unlock the 5 quests of item: 197349,197582,196967,197095, and (the deleted)203298.
Dragon Isles Drakes: White Scales (208550) unlock the 5 quests of item: 197393,197616,197146,197014, and 203354.

--item:197598 keep consistent with item:197396 use boss source "Decatriarch Wratheye"
\db\WindborneVelocidrake.lua
```
        name = "Windborne Velocidrake: Gray Hair",
        itemID = 197598,
        questID = 69802,
        source = sources.Dungeon,--replace sources.Chest,
        bossName = L["Decatriarch Wratheye"],--replace ChestName = L["Decay Tainted Chest"], this can be removed in local files
        zoneID = 13991,
```

--enums.lua: use local format for Fyrakk source
```
addon.Strings.Fyrakk = {}
addon.Strings.Fyrakk[1] = {
    enUS = L["Disciples of Fyrakk"],--replace "Disciples of Fyrakk",
}
addon.Strings.Fyrakk[2] = {
    enUS = L["Secured Shipment"],--replace "Secured Shipment",
}
```
also add 2 lines in local files
L["Disciples of Fyrakk"]
L["Secured Shipment"]

--there are 2 L["Lord Epochbrgl"]
e.g. in enus.lua 
code line 40 is duplicated with 61,remove one

--rare L["Gutrot Slime"] is 2nd stage of the rare:193225 "Notfar the Unbearable"
e.g. in enus.lua 
replace L["Gutrot Slime"] with L["Notfar the Unbearable"]

--"Groth", "Snee", and "Voll" are team members of L["Harkyn Grymstone"], they respawn all at once.
e.g. in enus.lua
remove L["Groth"], L["Snee"], and L["Voll"]

--L["Mokshoi"] is a spell mistake: "Moskhoi"
e.g. in enus.lua
replace L["Mokshoi"] with L["Moskhoi"]

**Comment by teelolws** [comment]
> --I also sugguest that Dragon Riding related items could use source "Dragon Riding" in the future version.

Some come from the daily quests, some come from achievements. I currently have these separated into Containers and Achievements. All the containers are dragon racing daily quest rewards, and all the achievement ones are dragon racing achievements. I could rename the existing 'Container' to 'Dragon Racing Containers', and the existing 'Achievement' to 'Dragon Racing Achievement', then if something changes in future I will adapt.

**Comment by teelolws** [comment]
> --Since you list the souces of "Armor" 197357,197588,197099,196961, which unlocked by spell:400549 awarded by quest:70911 after renown 26 with the Accord. (the 4 manucripts exist in client but not available actually)
To keep consistent, you may hide the 4 "Armor" or show the 4 "Helm", the souces of "Helm" 197373,197600,197119,196990 which unlocked by spell:409471 awarded by quest:75742 after renown 19 with the Niffen.(also exist but not available)
\db\RenewedProtoDrake.lua

I haven't checked recently, so maybe it was fixed in 10.1.5. I have the "Helm"s commented out because at the start of 10.1.0 they were causing errors: https://github.com/TLDRMissions/ManuscriptsJournal/commit/f153493a7c99d6b322d7f2b1a4d2feb8dbc3710d

**Comment by teelolws** [comment]
Yup the Helm data is still causing issues. Nothing from its item ID is loading in, causing the journal to fail to load that entry:

![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/49792789/271f6a2f-3494-4ef1-bc91-21e4263a2d86)

**Comment by teelolws** [comment]
> there're up to 5 items was removed from client, but item's original quest maybe still can be unlocked by other ways.

If the item was removed from the client then I won't be able to include it. All of its display information comes from the item ID!

**Comment by teelolws** [comment]
> --Dragon Isles Drakes: Gilded Armor (208200)
on the 10.1.7 ptr, there're 2 new items 208200 and 208550.
Dragon Isles Drakes: Gilded Armor (208200) unlock the 5 quests of item: 197349,197582,196967,197095, and (the deleted)203298.
Dragon Isles Drakes: White Scales (208550) unlock the 5 quests of item: 197393,197616,197146,197014, and 203354

**Comment by pepedressingroom** [comment]
> > there're up to 5 items was removed from client, but item's original quest maybe still can be unlocked by other ways.
> 
> If the item was removed from the client then I won't be able to include it. All of its display information comes from the item ID!

Sorry, I just compared the data with wowhead db, and did not test on client.
