### ISSUE TITLE
> 10.1.7 ptr

### ISSUE THREAD

**Issue by teelolws** [TLDRMissions/ManuscriptsJournal#15]
> --Dragon Isles Drakes: Gilded Armor (208200)
on the 10.1.7 ptr, there're 2 new items 208200 and 208550.
Dragon Isles Drakes: Gilded Armor (208200) unlock the 5 quests of item: 197349,197582,196967,197095, and (the deleted)203298.
Dragon Isles Drakes: White Scales (208550) unlock the 5 quests of item: 197393,197616,197146,197014, and 203354

_Originally posted by @teelolws in https://github.com/TLDRMissions/ManuscriptsJournal/issues/14#issuecomment-1656584358_

**Comment by pepedressingroom** [comment]
5 more manuscripts are sold by Maztha.(203355,203306,203319,203359,203336)
Maztha seems available only during the Kalimdor Cup or Eastern Kingdoms Cup
Eastern Kingdoms Cup runs from Oct 4th to Oct 17th. 

```
    {
        name = "Winding Slitherdrake: Yellow Scales",
        itemID = 203355,
        questID = 73846,
        source = sources.Vendor,
        vendorName = L["Maztha"],
        zoneID = 13862,
    },
```

```
    {
        name = "Winding Slitherdrake: Horned Brow",
        itemID = 203306,
        questID = 73794,
        source = sources.Vendor,
        vendorName = L["Maztha"],
        zoneID = 13862,
    },
```

```
    {
        name = "Winding Slitherdrake: Finned Cheek",
        itemID = 203319,
        questID = 73807,
        source = sources.Vendor,
        vendorName = L["Maztha"],
        zoneID = 13862,
    },
```

```
    {
        name = "Winding Slitherdrake: Shark Finned Tail",
        itemID = 203359,
        questID = 73851,
        source = sources.Vendor,
        vendorName = L["Maztha"],
        zoneID = 13862,
    },
```

```
    {
        name = "Winding Slitherdrake: Paired Horns",
        itemID = 203336,
        questID = 73826,
        source = sources.Vendor,
        vendorName = L["Maztha"],
        zoneID = 13862,
    },
```

4 new manuscripts are added for holiday.(208742,208680,208858,208859)
[Holiday Dragonriding Customizations Coming in Patch 10.1.7 - Wowhead News](https://www.wowhead.com/news/holiday-dragonriding-customizations-coming-in-patch-10-1-7-334048#news-post-334048)
```
    {
        name = "Renewed Proto-Drake: Brewfest Armor",
        itemID = 208742,
        questID = 77774,
        --source = ,
    },--Brewfest

    {
        name = "Windborne Velocidrake: Hallow's End Armor",
        itemID = 208680,
        questID = 77725,
        --source = ,
    },--Hallow's End

    {
        name = "Highland Drake: Pirates' Day Armor",
        itemID = 208858,
        questID = 77875,
        --source = ,
    },--Pirates' Day

    {
        name = "Cliffside Wylderdrake: Day of the Dead Armor",
        itemID = 208859,
        questID = 77876,
        --source = ,
    },--Day of the Dead
```

--Global Strings
BATTLE_PET_SOURCE_7 = "World Event";
CALENDAR_FILTER_HOLIDAYS = "Holidays";

**Comment by teelolws** [comment]
Great! Think I got them all.

**Comment by pepedressingroom** [comment]
Source/db/10-1.lua
code line 218
questID = 197349,--it's the itemID for Renewed Proto-Drake: Gold and White Armor

"Dragon Isles Drakes: Gilded Armor" unlocks 5 old manuscripts without sources, so these 5 manuscripts are not available separately.

Reference source: [Deciphering page for "Dragon Isles Drakes: Gilded Armor"](https://www.wowhead.com/spell=418518/deciphering)

itemID	questID(Deciphering)	manuscript-name
197349	69550	Renewed Proto-Drake: Gold and White Armor
197582	69786	Windborne Velocidrake: White and Pink Armor
196967	69167	Cliffside Wylderdrake: Gold and White Armor
197095	69296	Highland Drake: Gold and White Armor
203298	73786	Winding Slitherdrake: White and Gold Armor73786 (removed?)

The same with "Dragon Isles Drakes: White Scales"
itemID	questID(Deciphering)	manuscript-name
197393	69594	Renewed Proto-Drake: White Scales
197616	69820	Windborne Velocidrake: White Scales
197146	69347	Highland Drake: White Scales
197014	69214	Cliffside Wylderdrake: White Scales
203354	73845	Winding Slitherdrake: White Scales

Reference source: [Deciphering page for "Dragon Isles Drakes: White Scales"](https://www.wowhead.com/spell=419941/deciphering)

**Comment by pepedressingroom** [comment]
5 more manuscripts sold by Maztha are old manuscripts in db without sources.
They also exist in WindingSlitherdrake.lua.
Sorry, I did not make it clear.
Reference source:  [youtube:(EVERYTHING Coming in Patch 10.1.7@MrGM)12:38](https://youtu.be/DLJFqs__MCM?t=757)

**Comment by teelolws** [comment]
Okay, removed the duplicate data. The new "Dragon Isle Drakes" can replace the 5 individual items, since so far it looks like Blizzard won't be adding the individual items. Only need to check one of their quest IDs so I used the Renewed Proto Drake quest ID.

**Comment by teelolws** [comment]
I don't know where "Dragon Isles Drakes: White Scales" comes from so still don't have a source listed for it.

**Comment by pepedressingroom** [comment]
"Dragon Isles Drakes: White Scales"
Guess to be the new meta achievement relating to dragonriding races.

1.[Dragonriding Challenge: Dragon Isles: Bronze](https://www.wowhead.com/achievement=18790) reward: toy
2.[Dragonriding Challenge: Dragon Isles: Silver](https://www.wowhead.com/achievement=18791) reward: ?
3.[Dragonriding Challenge: Dragon Isles: Gold](https://www.wowhead.com/achievement=18792)  reward: title

Since Bronze and Gold list the reward on wowhead, personally I think it's the reward of Silver.
It will be clear after someone complete Bronze.

**Comment by teelolws** [comment]
Yeah thats my thought, too. I'll add the source once theres confirmation!
