### ISSUE TITLE
Error Loading both, CN and TW languages

### ISSUE THREAD

**Issue by Galthariel** [TLDRMissions/ManuscriptsJournal#17]
Here are the errors

2x Error loading ManuscriptsJournal/Locales/zhTW.lua
2x Error loading ManuscriptsJournal/Locales/zhCN.lua

**Comment by teelolws** [comment]
I've checked - those files are definitely in the .zip for the latest release. Most likely whatever you used to update your addons didn't install the latest release properly.

**Comment by Galthariel** [comment]
I used CurseForge App. Will try again and let you know

**Comment by Galthariel** [comment]
You're right. I think it was a CF glitch. No more issues :-)

Thanks
