### ISSUE TITLE
looted manuscript on second account, but addon says its not applying to main

### ISSUE THREAD

**Issue by FinestHour** [TLDRMissions/ManuscriptsJournal#24]
i looted a manuscript on my dual box account and learned it, however it does not seem to apply to my main one. last i checked manuscripts are all account wide right? maybe addon just not showing it right

![asdfasdf](https://github.com/TLDRMissions/ManuscriptsJournal/assets/5158869/0867766f-ab2d-46ad-9f54-3d31bbcd2836)

**Comment by teelolws** [comment]
Are they on the same bnet account? Maybe they need a relog after learning to update on other accounts, did you relog? ~~If you were watching it while learning on the other account, it won't automatically update. Needs at the minimum, a change of filter or a page scroll.~~

I've been told by other multiboxers that it doesn't update on alts until the character relogs. This is a restriction placed by Blizzard and theres nothing I can do to work around it.

Edit: I'm being told it updates on the alts after using a spell.

**Comment by FinestHour** [comment]
got it, it eventually updated! ty for swift answer
