### ISSUE TITLE
Bugsack Error

### ISSUE THREAD

**Issue by Rubyurek** [TLDRMissions/ManuscriptsJournal#25]
1476x ManuscriptsJournal/ui.lua:183: attempt to call method 'OnManuscriptsUpdated' (a nil value)
[string "@ManuscriptsJournal/ui.lua"]:183: in function <ManuscriptsJournal/ui.lua:181>

Locals:
self = ShapeshiftsJournal {
 0 = <userdata>
 LayoutCurrentPage = <function> defined @ManuscriptsJournal/ui.lua:929
 AcquireFrame = <function> defined @ManuscriptsJournal/ui.lua:112
 numPossibleShapeshifts = 0
 OnPageChanged = <function> defined @ManuscriptsJournal/ui.lua:172
 needsDataRebuilt = true
 RefreshView = <function> defined @ManuscriptsJournal/ui.lua:119
 PagingFrame = Frame {
 }
 Tab = CollectionsJournalSecureTab1 {
 }
 FullRefreshIfVisible = <function> defined @ManuscriptsJournal/ui.lua:830
 UpdateButton = <function> defined @ManuscriptsJournal/ui.lua:131
 needsRefresh = true
 tabName = "Shapeshifting"
 RefreshViewIfVisible = <function> defined @ManuscriptsJournal/ui.lua:835
 numKnownShapeshifts = 0
 iconsFrame = Frame {
 }
 SortShapeshiftsIntoEquipmentBuckets = <function> defined @ManuscriptsJournal/ui.lua:860
 itemIDsInCurrentLayout = <table> {
 }
 SortEquipBucketsIntoPages = <function> defined @ManuscriptsJournal/ui.lua:886
 shapeshiftLayoutData = <table> {
 }
 shapeshiftEntryFrames = <table> {
 }
 RebuildLayoutData = <function> defined @ManuscriptsJournal/ui.lua:843
 OnLoad = <function> defined @ManuscriptsJournal/ui.lua:813
}
event = "UNIT_SPELLCAST_SUCCEEDED"
(*temporary) = nil
(*temporary) = ShapeshiftsJournal {
 0 = <userdata>
 LayoutCurrentPage = <function> defined @ManuscriptsJournal/ui.lua:929
 AcquireFrame = <function> defined @ManuscriptsJournal/ui.lua:112
 numPossibleShapeshifts = 0
 OnPageChanged = <function> defined @ManuscriptsJournal/ui.lua:172
 needsDataRebuilt = true
 RefreshView = <function> defined @ManuscriptsJournal/ui.lua:119
 PagingFrame = Frame {
 }
 Tab = CollectionsJournalSecureTab1 {
 }
 FullRefreshIfVisible = <function> defined @ManuscriptsJournal/ui.lua:830
 UpdateButton = <function> defined @ManuscriptsJournal/ui.lua:131
 needsRefresh = true
 tabName = "Shapeshifting"
 RefreshViewIfVisible = <function> defined @ManuscriptsJournal/ui.lua:835
 numKnownShapeshifts = 0
 iconsFrame = Frame {
 }
 SortShapeshiftsIntoEquipmentBuckets = <function> defined @ManuscriptsJournal/ui.lua:860
 itemIDsInCurrentLayout = <table> {
 }
 SortEquipBucketsIntoPages = <function> defined @ManuscriptsJournal/ui.lua:886
 shapeshiftLayoutData = <table> {
 }
 shapeshiftEntryFrames = <table> {
 }
 RebuildLayoutData = <function> defined @ManuscriptsJournal/ui.lua:843
 OnLoad = <function> defined @ManuscriptsJournal/ui.lua:813
}
(*temporary) = "nameplate2"
(*temporary) = "Cast-3-4256-2548-1072-389572-004B52BDA9"
(*temporary) = 389572
(*temporary) = "attempt to call method 'OnManuscriptsUpdated' (a nil value)"

**Comment by teelolws** [comment]
Are you running the latest version? This was a bug that I fixed yesterday in https://github.com/TLDRMissions/ManuscriptsJournal/commit/872b28b825f246ec9210931bd53f98c4c3778623
