### ISSUE TITLE
Druid Travel Forms Pre Dragonflight 

### ISSUE THREAD

**Issue by Ravijioli** [TLDRMissions/ManuscriptsJournal#26]
The Druid Travel Forms pre-dragonflight dont seem to be doing an account wide unlock despite having all the forms. It will list some characters having the forms and list who has unlocked the forms, I log to them thinking it just needs to register that I have them to fully display them all and it doesnt. 

As seen here that I have them all unlocked: 
![have them all](https://github.com/TLDRMissions/ManuscriptsJournal/assets/150978744/1555cd23-36b3-4808-a1d5-142531fcb4ed)

but when I go to the manuscript journal this is what displays:
![where are they](https://github.com/TLDRMissions/ManuscriptsJournal/assets/150978744/aa50e2d9-b8f7-41be-9a07-9916c7e9f6af)

**Comment by teelolws** [comment]
If you're saying there are account-wide glyph unlocks that don't flag the questID as completed on the alts, I might not be able to do anything. I'd need to find a way to detect that the alt has access to the glyph without checking the questID. I could maybe store completed questIDs into the saved variables but would need a list of which ones are account wide.
