### ISSUE TITLE
All demon appearances geyed out

### ISSUE THREAD

**Issue by flow0284** [TLDRMissions/ManuscriptsJournal#29]
While playing my Warlock with the german client, alle demon appearances are greyed out. Of course i dont have all claimed but i have the most of them.

![grafik](https://github.com/TLDRMissions/ManuscriptsJournal/assets/27314841/2f8815bb-de16-4876-a52f-fa257c698509)

**Comment by teelolws** [comment]
I've had reports that if you learn the grimoire on one character, they will be greyed out on another character despite being account-wide. Its on my list to find a workaround for that.
