### ISSUE TITLE
Error when opening options panel

### ISSUE THREAD

**Issue by jungheeMW** [TLDRMissions/ManuscriptsJournal#34]
Getting the following error when opening the Options panel from the Game Menu

https://pastebin.com/2A04mtBW

**Comment by teelolws** [comment]
This is a problem with Angry Keystones using an older version of the LibUIDropDownMenu library. I have reported the compatibility issue to the LibUIDropDownMenu developer: https://legacy.curseforge.com/wow/addons/libuidropdownmenu/issues/20
