### ISSUE TITLE
3x ...Journal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1512: attempt to index field 'NewFeature' (a nil value)

### ISSUE THREAD

**Issue by BigFire321** [TLDRMissions/ManuscriptsJournal#35]
3x ...Journal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1512: attempt to index field 'NewFeature' (a nil value)
[string "@ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1512: in function `UIDropDownMenu_Refresh'
[string "@ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua"]:1587: in function `UIDropDownMenu_SetSelectedID'
[string "@AnnounceInterrupts/ai.lua"]:232: in function <AnnounceInterrupts/ai.lua:115>
[string "@AnnounceInterrupts/ai.lua"]:354: in function `?'
[string "@AnnounceInterrupts/ai.lua"]:338: in function <AnnounceInterrupts/ai.lua:337>

Locals:
self = <table> {
 UIDropDownMenu_SetButtonText = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2085
 containsMouse = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1920
 UIDropDownMenu_DisableButton = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2069
 Create_UIDropDownCustomMenuEntry = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2293
 UIDropDownMenu_Refresh = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1448
 UIDropDownMenu_Initialize = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:762
 UIDropDownMenu_SetSelectedName = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1568
 UIDropDownMenu_SetDropDownEnabled = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2111
 UIDropDownMenu_SetInitializeFunction = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:789
 UIDropDownMenu_GetSelectedID = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1594
 UIDropDownMenu_MatchTextWidth = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1953
 DropDownExpandArrowMixin = <table> {
 }
 UIDropDownMenuButton_ShouldShowIconTooltip = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:118
 UIDropDownMenu_InitializeHelper = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:92
 DropDownMenuButtonMixin = <table> {
 }
 UIDropDownMenuButton_GetName = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2055
 UIDropDownMenu_ClearAll = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2000
 UIDropDownMenu_GetCurrentDropDown = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2043
 UIDropDownMenu_JustifyText = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2019
 UIDropDownMenu_IsEnabled = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2160
 UIDropDownMenu_RefreshDropDownSize = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:820
 UIDropDownMenu_EnableButton = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2073
 UIDropDownMenu_SetFrameStrata = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:816
 UIDropDownMenu_AddButton = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:985
 UIDropDownMenu_GetButtonWidth = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1400
 CloseDropDownMenus = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1881
 UIDropDownMenu_HandleGlobalMouseEvent = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1925
 ColorPicker_GetPreviousValues = <function> defined @AngryKeystones/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:2158
 Create_UIDropDownMenu = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:748
 UIDropDownMenu_SetButtonWidth = <function> defined @ManuscriptsJournal/libs/LibUIDropDownMenu/LibUIDropDownMenu.lua:1980
 UIDropDownCustomMenuEntryMixin = <table> {
 }
 UIDropDownMenuButton_OpenColorPicker = <function> defined @ManuscriptsJournal

**Comment by teelolws** [comment]
>  [string "@AnnounceInterrupts/ai.lua"]:232: in function <AnnounceInterrupts/ai.lua:115>

Ask the author of that addon "AnnounceInterrupts" to update their libraries.
