### ISSUE TITLE
Due to SecureTabs-2.0 Not utilizing numTabs and selectedTab using GetID() ~= 4 causes conflicts with Addons that SetID property 

### ISSUE THREAD

**Issue by MrExillion** [TLDRMissions/ManuscriptsJournal#37]
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/0a068500-49af-4d7e-9061-47daac0760c5)
Consider The following change:

```LUA
-- ui.lua line 139
hooksecurefunc("CollectionsJournal_SetTab", function(self, tabID)
    -- if tabID ~= CollectionsJournalTab4:GetID() then
    --[[ instead the below logic checks for the case that any ID modification to the SecureTabs-2.0 tabs will not break ManyscriptsJournal if Overridden.
    Neither if SecureTabs-2.0 is later updated to match the Blizzards tab system.]]--
        if  tabID ~= CollectionsJournalTab4:GetID() and not tContains(ParentMixin:GetAllPanels(),self.Tabs[tabID or 1].frame) then    
        ManuscriptsSideTabsFrame:Hide()
        for _, journal in pairs(ParentMixin:GetAllPanels()) do
            journal:Hide()
        end
    end
end)
```

Alternatively: consider using hooksecurefunc to call an overrideable callback function  =>

```LUA
-- ui.lua line 139
function addon.CollectionsJournal_SetTabCallback(frame,tabID) 
     if tabID ~= CollectionsJournalTab4:GetID() then
         ManuscriptsSideTabsFrame:Hide()
         for _, journal in pairs(ParentMixin:GetAllPanels()) do
             journal:Hide()
         end
     end
end
-- line 139 => line 162
hooksecurefunc("CollectionsJournal_SetTab",function(self,tabID)
    local relay = self;
    addon.CollectionsJournal_SetTabCallback(relay,tabID) 
end)
```

Although one should be careful with overrides considering multiple addons can try to override and taint the same thing, hence why hooksecurefunc is a thing in the first place. My own interest in this is that I don't like SecureTabs-2.0 as they aren't actually secure, and causes problems for my addon users in return. Addon Tabs should in my opinion append the numTabs the way blizzard checks things, and use the standard Blizzard template, to be able to hook functionality to other addons dynamically and safely even if they use a different library than our own. karmaLib was created for similar reasons when rock and ace had some lib conflicts, although I am not sure how widespread it was adopted. I would love to make a pull-request for for the SecureTabs-2.0 which essentially handles addon tabs as if they were Blizzards, while keeping them properly secure. The issue is I also run into Addons like this one, where I find they are relying on the absence of ID's. Therefore I am raising it as an Issue with a few suggestions so you can evaluate your own position on things, while I also provide a few possible solutions, should SecureTabs-2.0 ever change in such a way that it would break your AddOn, regardless if the change comes as a result of my pullrequest or not.

**Comment by teelolws** [comment]
I have had problems with SecureTabs-2.0 for a long time. I had to create a secure action button that is clicked instead of the SecureTabs-2.0 button to switch to the Heirlooms tab, which is unreliable if another addon does stuff to the Heirlooms tab. SecureTabs offers an OnDeselect property but never implemented it, the author never responded to my PR to implement it. If you have a suggestion of a better library, I can look at switching to it.

As for your code, I'm not sure what this is ever going to accomplish:

```LUA
not tContains(ParentMixin:GetAllPanels(), self.Tabs[tabID or 1].frame)
```

`ParentMixin:GetAllPanels()` has the frames like ManuscriptsJournal, not the tabs. They should never be in CollectionsJournal.Tabs?

Your second code example just appears to do the same as the original but with a couple of extra steps?

**Comment by MrExillion** [comment]
> I have had problems with SecureTabs-2.0 for a long time. I had to create a secure action button that is clicked instead of the SecureTabs-2.0 button to switch to the Heirlooms tab, which is unreliable if another addon does stuff to the Heirlooms tab. SecureTabs offers an OnDeselect property but never implemented it, the author never responded to my PR to implement it. If you have a suggestion of a better library, I can look at switching to it.
> 
I am so happy to hear I am not alone with the struggle. I don't think it's better but Ace3.0 does have a Tabs thing.
I am seriously considering just writing an extension to the library or writing my own library in a few months that will do things the proper way.

> As for your code, I'm not sure what this is ever going to accomplish:
> 
> ```lua
> not tContains(ParentMixin:GetAllPanels(), self.Tabs[tabID or 1].frame)
> ```
> 
> `ParentMixin:GetAllPanels()` has the frames like ManuscriptsJournal, not the tabs. They should never be in CollectionsJournal.Tabs?
> 

CollectionsJournal does not have the Tabs table by default, it is added by the Library I think, I am not actually sure... not yet at least I can get back to you on this one.
The fact is we actually get a nice little Tabs table that looks like this:

![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/b64fda26-5d0d-4401-9187-85f66fb18ffd)

In otherwords, `self.Tabs[6].frame == ManuscriptJournal`. So by using `tabID or 1`  we never try to index a nil value, but 1 will never be return true becuase its one of Blizzard's ID's  By checking with `not tContains(ParentMixin:GetAllPanels(),self.Tabs[tabID or 1].frame)` we find if the Frame associated with your tab exist in your table of Panels, and if it does, then it then it returns true, so only yourown frames will ever be applicable for your side tabs. However. You could also make another check and then add an API which is MUCH MUCH safer, than my other suggestion. If you have a table of addons that wants to use your side tabs, then you just allow addons to append your table:
```LUA 
local exceptionPanels = { };

-- consider the not tContains(ParentMixin:GetExceptionPanels(),self.Tabs[tabID or 1].frame) as containing All your panels by default + whatever other addons have registered OnLoad.


local function ParentMixin:GetExceptionPanels()
    return exceptionPanels;
end

function addon.RegisterExceptionPanels(panel)
    if(type(panel) = {}) then 
       for _, p in ipairs(panel) do
            exceptionPanels[#exeptionPanels] = p;
       end
    else
        exceptionPanels[#exceptionPanels] = panel;
    end
end

    addon.RegisterExceptionPanels(ParentMixin:GetAllPanels()); -- This can be called anywhere as it is name spaced and scoped to global. So lets say I made another AddOn that wants to use the tabs you made on my tab.panel then i just need to do the same

    ManuscriptJournal.RegisterExceptionPanels(myAddonsPanels); -- it can be both a table or a single panel if done right. 

```


> Your second code example just appears to do the same as the original but with a couple of extra steps?

Actually no, the second code example does what yours does no changes, except the hooksecurefunc() now hooks a function that can be accessed through your addon as namespace i.e.

```LUA
    ManuscriptsJournal.CollectionsJournal_SetTabCallback(self,anyTabIDYouWishToSwitchTo);
``` 
you can hookthiscallback as shown. Say I wanted to, i shouldn't but say I did anyway, want to do something with youraddon but change the condidtion, say have the side tabs open on MyAddons Tab or NOT have them open on my addons tab... then all i need to do is to Override the method and use it as base while change the logic a little bit. now when the hook is called, its calling my Override rather than your function, and I will never have to "pull-request" you to do any work, in the sense that technically speaking i am tainting your code. Now the responsibility of keeping compatibility is on my end. Its a bit invasive, and therefore it shouldn't be done, and especially not if many people do this. Then it gets really messy and really bad. So I wouldn't reccomend this approach in general.

The override or hook could look like this: 
```LUA
-- Overide
local aliasRef = ManuscriptsJournal;

function aliasRef:CollectionsJournal_SetTabCallback(frame,tabID)
--- do my override code here ... it's essentially the same as Replacing the function body
end

-- hooking
hooksecurefunc(aliasRef, "CollectionsJournal_SetTabCallback", function(self,tabID) end);

```
I wouldn't reccomend do this anymore, i think the `addon.RegisterExceptionPanels(ParentMixin:GetAllPanels());` is a smarter option.

**Comment by teelolws** [comment]
Okay, I'll add the tcontains check. I'm not going to invest time in making the addon open to full interference from other addons though.

**Comment by MrExillion** [comment]
I Will be in touch some time later, I am seriously considering making a proper library that also handles "SecureTab-2.0" but with the feature that it can be deactivated per addon on demand. I am going to have to remake some large parts of my tab hooking at some point. And I might as well solve both our problems. Let me know if you have any particular struggles with the SecureTab-2.0 library you'd like fixed or added in a future library from me, and I will include it. It might take a few months before i make it though.

**Comment by teelolws** [comment]
If you do that, make the tab buttons SecureActionButtons so they can be assigned a different tab that they click. Just be mindful of the restrictions around secure buttons when you design it.

Eg: I want my tab button to click the Heirlooms tab securely, as I designed manuscripts journal to sit in front of the heirlooms tab. I can't call Heirlooms:Show() while in combat, but a secure action button can.

**Comment by MrExillion** [comment]
> so they can be assigned a different tab that they click.

can you elaborate? I am not 100% sure what you mean by this. Do you mean such that if i click Tab A then it reveals Tab B.Panel?

**Comment by teelolws** [comment]
See: https://github.com/TLDRMissions/ManuscriptsJournal/blob/main/Source/ui.lua#L20-L32

My secure button uses

```LUA
secureTabButton:SetAttribute("type", "click")
secureTabButton:SetAttribute("clickbutton", CollectionsJournalTab4)
```

to click the Heirlooms Tab in a way that it will be run without tainting the Collections Journal. This can show the Heirlooms Tab while in combat without breaking anything.

If the library used a Secure Action Button then I wouldn't need to make a second button.

**Comment by MrExillion** [comment]
> See: https://github.com/TLDRMissions/ManuscriptsJournal/blob/main/Source/ui.lua#L21
> 
> My secure button uses
> 
> ```lua
> secureTabButton:SetAttribute("type", "click")
> secureTabButton:SetAttribute("clickbutton", CollectionsJournalTab4)
> ```
> 
> to click the Heirlooms Tab in a way that it will be run without tainting the Collections Journal. This can show the Heirlooms Tab while in combat without breaking anything.
> 
> If the library used a Secure Action Button then I wouldn't need to make a second button.

I see so you want to be able to keep the in Battle functionality, I never had that issue due to iStableMaster requiring talking to a StableMaster, while not in combat. 


Technically speaking using SetID and CollectionsJournal_SetNumTabs()  is taint, but it is intended to be used as Appending. So in this way it will always dynamically hook using blizzards own SharedXML functions. While it is strictly speaking taint, it's not harmful, and cannot be harmful if its only ever appending as if it was a Stack.Push(), if we ddid Stack.Pop() it would be a different story. The important thing is we don't actually change any XML and only increment accessible numbers that function as record and a size lookup. if we only expand the size we never actually end up tainting anything. Its a bit like doing Override, and then executing base.Function(); and then do more stuff. Anyway, making them like SecureActionButtons, might be possible, but it will probably require inheriting from multiple XML templates. I will reference this issue in my own issue tracker, and list it as a feature to do.

**Comment by teelolws** [comment]
More importantly: I want to be able to call HeirloomsJournal:Show() while in combat.

But if you have a solution for SetID and CollectionsJournal_SetNumTabs issues go for it.

**Comment by teelolws** [comment]
> it will probably require inheriting from multiple XML templates

Yes thats possible and simple enough. In SecureTabs-2.0 it could be done by changing 

```LUA
	local tab = CreateFrame('Button', '$parentSecureTab' .. id, panel, self.template)
```

to

```LUA
	local tab = CreateFrame('Button', '$parentSecureTab' .. id, panel, self.template..", SecureActionButtonTemplate")
```

Though I would also have to change other stuff in the library to not change the size/position/enable/disable while in combat.

And 

```LUA
tab:SetScript('OnClick'
```

Would become HookScript.

**Comment by MrExillion** [comment]
> > it will probably require inheriting from multiple XML templates
> 
> Yes thats possible and simple enough. In SecureTabs-2.0 it could be done by changing
> 
> ```lua
> 	local tab = CreateFrame('Button', '$parentSecureTab' .. id, panel, self.template)
> ```
> 
> to
> 
> ```lua
> 	local tab = CreateFrame('Button', '$parentSecureTab' .. id, panel, self.template..", SecureActionButtonTemplate")
> ```
> 
> Though I would also have to change other stuff in the library to not change the size/position/enable/disable while in combat.
> 
> And
> 
> ```lua
> tab:SetScript('OnClick'
> ```
> 
> Would become HookScript.

You can concatinate templates Inheritance like this?

**Comment by teelolws** [comment]
Yup!

See FrameXML\TargetFrame.xml:

```XML
	<Button name="BossTargetFrameTemplate" inherits="TargetFrameTemplate, PingableUnitFrameTemplate" mixin="BossTargetFrameMixin" toplevel="false" virtual="true">
```

Blizzard does it.

**Comment by MrExillion** [comment]
> Yup!
> 
> See FrameXML\TargetFrame.xml:
> 
> ```
> 	<Button name="BossTargetFrameTemplate" inherits="TargetFrameTemplate, PingableUnitFrameTemplate" mixin="BossTargetFrameMixin" toplevel="false" virtual="true">
> ```
> 
> Blizzard does it.



I assume this is just stacking XML tags then?

You can follow the progress on the Library here: [iStableMaster_Library-Feature. Tags: Backlog, Requests](https://legacy.curseforge.com/wow/addons/istablemaster/issues/60) I will replace this with project path eventually.

**Comment by teelolws** [comment]
Yes but it works in CreateFrame() too. 

https://warcraft.wiki.gg/wiki/API_CreateFrame

> string? - Comma-delimited list of [virtual XML templates](https://warcraft.wiki.gg/wiki/Virtual_XML_template) to inherit;

**Comment by MrExillion** [comment]
> Yes but it works in CreateFrame() too.
> 
> https://warcraft.wiki.gg/wiki/API_CreateFrame
> 
> > string? - Comma-delimited list of [virtual XML templates](https://warcraft.wiki.gg/wiki/Virtual_XML_template) to inherit;

At first i didn't spot your mistake, with the missing ", " so i thought it was just '..'! But this makes perfect sense.

Although I think i need to do more than just concatiante them I might need to be a bit surgical, but it can be done I have some really complicated XML templates using prepend and appends that makes it possible to handle these all from the instantiation:

![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/3b609dc1-469d-411a-b444-b724fc564fdd)
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/5c1f40d4-fa82-4e11-a785-050ac49dc4e8)


Which essentially replaced the horrible maintenance of managing the equivalent of the "cards" which still looks like this:

![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/3ee9b8f5-2a1b-4885-99c0-c0972051c29b)
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/6b2d4554-6a5e-434c-8577-607c9becda71)
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/377575cc-c98b-43a8-94d6-3a86901c9fc4)


The Point is.... Making it work is always possible but templates exist for a reason!


(Before you ask if i didn't use loops? These are in the loops!!!)

**Comment by MrExillion** [comment]
> `ParentMixin:GetAllPanels()` has the frames like ManuscriptsJournal, not the tabs. They should never be in CollectionsJournal.Tabs?


I promiesd i would get back to you:

CollectionsJournal.Tabs Appears to my surprise to be Native to Blizzard, I had a situation a few days ago where it appeared as if it was an Addon, but it might have been a bug. I am investigating, but I think Blizzard has some failsafe where it keeps track of something, to some degree. I am not sure yet. But you shouldn't be unable to access it at all while you use the SecureTabs-2.0 Library, so your change should be stable.

**Comment by teelolws** [comment]
If you're writing a library you cannot use XML. You will get "Template already declared" errors if more than one addon implements your library. Its one of the unfortunate sacrifices libraries have to make.

**Comment by teelolws** [comment]
.Tabs comes from SharedXML\SharedUIPanelTemplates.xml:

```XML
<Button name="PanelTabButtonTemplate" mixin="PanelTabButtonMixin" motionScriptsWhileDisabled="true" parentArray="Tabs" virtual="true" >
```

The `parentArray="Tabs"` part means the parent frame, which in this case becomes CollectionsJournal, creates an array .Tabs indexed by the ID. The IDs are defined in Blizzard_Collections.xml

```XML
<Button name="$parentTab1" inherits="CollectionsJournalTab" text="MOUNTS" id="1">
```

It only seems to be referenced once, in SharedUIPanelTemplates.lua:

```LUA
local function GetTabByIndex(frame, index)
	return frame.Tabs and frame.Tabs[index] or _G[frame:GetName().."Tab"..index];
end

function PanelTemplates_UpdateTabs(frame)
	if ( frame.selectedTab ) then
		local tab;
		for i=1, frame.numTabs, 1 do
			tab = GetTabByIndex(frame, i);
			if ( tab.isDisabled ) then
				PanelTemplates_SetDisabledTabState(tab);
			elseif ( i == frame.selectedTab ) then
				PanelTemplates_SelectTab(tab);
			else
				PanelTemplates_DeselectTab(tab);
			end
		end
	end
end
```

**Comment by teelolws** [comment]
As .Tabs is defined in XML it should be one of the first things loaded in when Blizzard_Collections loads. I cannot imagine a time when its ever not defined aside from addon interference.

**Comment by MrExillion** [comment]
> As .Tabs is defined in XML it should be one of the first things loaded in when Blizzard_Collections loads. I cannot imagine a time when its ever not defined aside from addon interference.

I have been reading the Documentation for a while now, it looks like Blizzard is using some arraykey to keep updating the tabs if they are made from their templates. The Table parent.Tabs is not defined in XML anywhere its instantiated and updated.

[See](https://github.com/tomrus88/BlizzardInterfaceCode/tree/master/Interface/SharedXML/TabSystem)

**Comment by teelolws** [comment]
The collections tabs don't use TabSystemButtonTemplate. The only frame that does is the Professions window. Collections journal uses PanelTabButtonTemplate which is in SharedUIPanelTemplates

**Comment by MrExillion** [comment]
Maybe, I am too tired to keep going tonight, it's been a long day i need some food and then some sleep. I will let you know if I figure something out, all I can say is that the .Tabs Array can 100% be appended, and it appears as if the SecureTabs-2.0 Library does this inherently, without ever explicitly asking it to, from what I can see, however, it also appears as if the "cover" is being listed as a tab inadvertently. But i need some rest. Thanks for the exchange tonight, I will look more at this thursday or friday i think.

**Comment by teelolws** [comment]
The "cover" is something I never truly understood. It sits over the main tab, but... not sure why as he never implemented OnDeselect. It detects when we click back to the last selected tab, but doesn't care if we select a different tab?

**Comment by MrExillion** [comment]
> The "cover" is something I never truly understood. It sits over the main tab, but... not sure why as he never implemented OnDeselect. It detects when we click back to the last selected tab, but doesn't care if we select a different tab?

I think it might be a lecay thing to give the visual indication of the selected tab. There's only one that is moved across all the tabs when they are active.

the other possibility is that it is a "safety" in terms of being able to do things that are otherwise locked away a bit like the SecureActionButtons, but it just doesn't seem like the best solution since DF was released. The new tabs and the templates that blizzard have been working on the past 10+ years are getting closer and closer to something that is essentially super high-level prog. with front end layers only. I.e. I don't see how this would't eventually render libraries more or less obsolete in this particular case.

**Comment by Gaviin1242** [comment]
I assume (?) this is the cause of no longer being able to select the Manuscripts tab in my collections pane.  I can click the tab, but the content doesn't actually change to show the manuscripts.  Any plans on a fix?

**Comment by MrExillion** [comment]
> I assume (?) this is the cause of no longer being able to select the Manuscripts tab in my collections pane. I can click the tab, but the content doesn't actually change to show the manuscripts. Any plans on a fix?

That's hard to assume, or answer are you using other Addons that use SecureTabs-2.0? Or other tabs in the CollectionsJournal other than the standard ones?

**Comment by Gaviin1242** [comment]
I use two addons that seem to add tabs to that window:  Rematch, and PetTracker.

Looks like PetTracker uses SecureTabs-2.0, but Rematch doesn't.  PetTracker has a changelog entry on 12/7/23 about updating libraries.  I wonder if that's what broke it for ManuscriptsJournal.  :(

**Comment by teelolws** [comment]
Tried with ManuscriptsJournal, PetTracker, and Rematch, not getting any problems with the buttons.

**Comment by MrExillion** [comment]
Both ManuscriptsJournal and PetTracker with the JournalTab Enabled causes an issue with ManuscriptsJournal's tab, but its possible it might be fixed in a scheduled update if Teelo doesn't seem to be able to replicate the issue. But I can confirm I have seen it happen the moment ManuscriptsJournal is paired with another Addon using SecureTabs-2.0, I haven't been able to nail down the issue myself yet, but this is not the same issue as the GetID() ~= 4 thing, this affects the side tabs first and foremost.
Not the the SecureTab.

**Comment by teelolws** [comment]
The only changes I have made that I haven't published were changes to the dropdown menu system. I'm otherwise running the latest versions of ManuscriptsJournal and PetTracker, with no other addons turned on, and am not getting the issue. It picks the button and opens the frame as expected:
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/49792789/ace080bc-3c34-4800-ba8e-e7b1a4c8b555)

Any settings in either addon you think are relevant that I need to pick?

**Comment by MrExillion** [comment]
When i run the those two addons in particular nothing else then Manuscripts will throw out Rivals to the right, and the tab system breaks down, is the library using a packaging line to include a newer version than you have embedded perhaps? Or maybe this has to do with some persistent data in some saved variables? I will see if I remember it, but if i do i will show you a picture tomorrow of what it looks like for me, no alterations. Regardless its a different issue.

**Comment by teelolws** [comment]
If I change the loading order so PetTracker loads in first then the only difference is I don't get my OnDeselect functionality, so my sidebar remains when the Rivals tab is selected. Otherwise, I can't find a way to make these tabs not load in.

**Comment by MrExillion** [comment]
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/c83bcde4-4063-43ae-ba53-102f414e99e1)
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/9962c5fc-1bb2-46c0-8982-54f9729d509c)
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/10505ec0-c7ad-40bd-9f0c-a5f0bb0b065d)
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/b3b7f0cb-75f8-4af8-b4f1-f152b3b8ca44)


This below would be an example of the GetID issue, although this might not be to do with ManuscriptsJournal, this would likely be Rematch or PetTracker's doing:
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/20932320/58c53f19-8e0a-4e29-bd87-d641e6686c87)


But i dont seem to be able to replicate the issue myself anymore, IDK what changed.

**Comment by teelolws** [comment]
I don't see any problems with those screenshots?

If you mean the button being mouseovered while it is selected: 
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/49792789/94c21e37-534f-4487-8aa8-e66a427f70b6)

then that is because I have two buttons for the tab and it will happen even if ManuscriptsJournal is the only addon:
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/49792789/e28f4da4-bd7c-4e2e-98d2-c5c510035905)
