### ISSUE TITLE
No filtering for class-specific glyphs

### ISSUE THREAD

**Issue by Amethice** [TLDRMissions/ManuscriptsJournal#39]
The class-specific "glyphs" pane (for hunter books, druid customizations etc) do not have any filtering possible for things like known/unknown like the drake manuscripts and soulshapes do. It would be amazing if that could be added.

**Comment by teelolws** [comment]
I decided to leave that out since theres not many of them at this stage. Maybe if we get enough of them that they go beyond two pages, I'll look at porting those filters!

**Comment by Amethice** [comment]
Fair. I put the ticket up because the druid one has two pages for me atm. =)
