### ISSUE TITLE
Druid glyphs not reported for alts

### ISSUE THREAD

**Issue by Amethice** [TLDRMissions/ManuscriptsJournal#40]
A bit of a weird one, but I was looking at the druid forms I was issing and saw a few marked as not collected that I'm sure I have, so I checked the barber shop and confirmed it.

Basically, it only shows the glyph-based ones (at least the pre-DF glyphs, I don't have the golden stag form to verify the new one) as collected if the glyph was used on the same character, otherwise it's marked as incomplete. I'm assuming this has to do with a character-specific tracking quest of some kind used to show whether they have been learned, but hopefully there's some way around it.

UPDATE: Can verify that it seems like an implementation thing on Blizzard's end - if I track the "quest completed by" tooltip on the various items, then the more recent ones learned show as quest completed by every character, even non-druids. But the glyphs only show as quest completed for the single character who used the glyph.

**Comment by Amethice** [comment]
Have checked, and the Warlock glyphs don't have this problem so it's just the druid glyphs.

**Comment by teelolws** [comment]
I did some work a while back trying to get it to save those into the saved variables. It won't work across accounts but should share them across druids on the same account. Try that change and lmk if it works.

**Comment by Amethice** [comment]
That definitely does seem to work. It's not really as smooth as we might like, but from what I can tell, that's really the only way to do it beyond polling the barber shop when it's open, right? (Since the C_Barbershop functions for appearances known returns empty when you're not in the UI)

**Comment by teelolws** [comment]
The problem with the C_Barbershop functions is even if I check it while its open:

1. My addon isn't loaded until Blizzard_Collections is loaded
2. The database I use doesn't have any of the barbershop IDs mapped in, and its not something I'm keen to spend time collecting

**Comment by Amethice** [comment]
Yeah, I 100% understand you there. It's a PitA, but one caused on Blizzard's end. I think I can manage to edit the save data variables well enough to collate my data across accounts, at least. I looked at it, and it doesn't look complicated.
