### ISSUE TITLE
Manuscript menu overlays over other menus

### ISSUE THREAD

**Issue by Alfakennyone** [TLDRMissions/ManuscriptsJournal#42]
![image](https://github.com/TLDRMissions/ManuscriptsJournal/assets/61605997/ec3150e3-4b41-45e2-a28b-81cb5ecb861b)

I have to click on heirloom tab first so it fixes

**Comment by teelolws** [comment]
Does it happen with all other addons disabled?

**Comment by Alfakennyone** [comment]
> Does it happen with all other addons disabled?

yes it does
