### ISSUE TITLE
New Remix gems not showing up in Remix

### ISSUE THREAD

**Issue by aa-chrismcfadyen** [TLDRMissions/ManuscriptsJournal#43]
I'm on a level 37 Remix Shaman and the only tabs that display for me are Manuscripts and Hex

**Comment by teelolws** [comment]
No Gems tab at the bottom?

**Comment by aa-chrismcfadyen** [comment]
This is what the panel has for me:
![manuscripts](https://github.com/TLDRMissions/ManuscriptsJournal/assets/123623/5a9cdc73-01b9-4718-b2d5-315e3071e003)

**Comment by teelolws** [comment]
Whats the output if you run:

/dump C_UnitAuras.GetPlayerAuraBySpellID(424143)

**Comment by aa-chrismcfadyen** [comment]
![auraoutput](https://github.com/TLDRMissions/ManuscriptsJournal/assets/123623/7623c862-7133-4c52-8830-82a846e610f5)

**Comment by teelolws** [comment]
Thats as expected then. Addon interference, maybe? Does it work if you turn off all other addons?

**Comment by aa-chrismcfadyen** [comment]
It does show up as the only addon enabled.  So it looks like it's from another addon.  It's constantly making gem and page flip noises while it's open, and if I use it to swap meta gems or cogwheels, the game locks up briefly (though that is handy).

Is it supposed to show gems/tinkers you haven't acquired?

**Comment by teelolws** [comment]
If you can isolate which addon is causing the interference, I can try and find a workaround.

No, it currently only shows your items in your bags. I haven't finished making it yet!

**Comment by aa-chrismcfadyen** [comment]
Ah, looking forward to the rest!

I can probably get around to seeing what other addon is interfering later tonight, I have a bit too much to do right no to figure that out though (I have many addons)

**Comment by aa-chrismcfadyen** [comment]
After enabling my regular addons again, the Gems tab is there... so I'm not sure what it was!  It definitely wasn't because I hadn't reloaded since I updated, since I reloaded a few times trying to figure out the issue.
