### ISSUE TITLE
Tab in Collections not showing up.

### ISSUE THREAD

**Issue by rjmessing** [TLDRMissions/ManuscriptsJournal#45]
I wanted to see what I was missing for Dragonflight mount manuscripts and I can't find the tab anywhere.

![image](https://github.com/user-attachments/assets/6306d13e-800b-4b4b-bb34-d79e7e9254da)

**Comment by rjmessing** [comment]
I have verified that it works when all addons but Manuscripts, libuidrop down and secure tabs are disabled.

**Comment by teelolws** [comment]
Can you identify which addon is breaking it?

**Comment by rjmessing** [comment]
After going through all the add-ons to figure out which was breaking it, I found that it wasn't even enabled.  I thought I had enabled it after enabling all mods that had been updated to the pre-patch version.
