### ISSUE TITLE
WoW Patch 11.0.2.56110 and ManuscriptsJournal-11.0-001 error on load

### ISSUE THREAD

**Issue by fraerie** [TLDRMissions/ManuscriptsJournal#46]
1x ManuscriptsJournal/ui.lua:269: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@ManuscriptsJournal/ui.lua"]:269: in function <ManuscriptsJournal/ui.lua:268>
[string "@Blizzard_SharedXML/EventUtil.lua"]:74: in function <Blizzard_SharedXML/EventUtil.lua:66>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua"]:9: in function <...ns/Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua:8>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventoryClient.lua"]:935: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13471: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13494: in function `BlizzardAPIHook'
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
(*temporary) = nil
(*temporary) = "ManuscriptsJournal"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
addonName = "ManuscriptsJournal"
addon = <table> {
 soulshapeDB = <table> {
 }
 FilterComponent = <table> {
 }
 ParentMixin = <table> {
 }
 TameTomesDB = <table> {
 }
 db = <table> {
 }
 itemIDToDB = <table> {
 }
 HexTomesDB = <table> {
 }
 ShapeshiftDB = <table> {
 }
 PolymorphTomesDB = <table> {
 }
 manuscriptSpellIDs = <table> {
 }
 MOPRemixGemsDB = <table> {
 }
 spellIDToDB = <table> {
 }
 GrimoiresDB = <table> {
 }
 FilterDropDownSystem = <table> {
 }
 Enum = <table> {
 }
 Strings = <table> {
 }
}

**Comment by fraerie** [comment]
Also:

1x ManuscriptsJournal/SoulshapesTab.lua:605: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@ManuscriptsJournal/SoulshapesTab.lua"]:605: in function <ManuscriptsJournal/SoulshapesTab.lua:604>
[string "@Blizzard_SharedXML/EventUtil.lua"]:74: in function <Blizzard_SharedXML/EventUtil.lua:66>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua"]:9: in function <...ns/Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua:8>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventoryClient.lua"]:935: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13471: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13494: in function `BlizzardAPIHook'
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
(*temporary) = nil
(*temporary) = "ManuscriptsJournal"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
addonName = "ManuscriptsJournal"
collectedSoulshapeFilter = true
uncollectedSoulshapeFilter = true
soulshapeSoulshapeFilter = true
crittershapeSoulshapeFilter = true

**Comment by fraerie** [comment]
Also:

1x ManuscriptsJournal/export.lua:17: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@ManuscriptsJournal/export.lua"]:17: in function <ManuscriptsJournal/export.lua:16>
[string "@Blizzard_SharedXML/EventUtil.lua"]:74: in function <Blizzard_SharedXML/EventUtil.lua:66>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua"]:9: in function <...ns/Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua:8>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventoryClient.lua"]:935: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13471: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13494: in function `BlizzardAPIHook'
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
(*temporary) = nil
(*temporary) = "ManuscriptsJournal"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
addonName = "ManuscriptsJournal"

**Comment by fraerie** [comment]
Also:

1x ManuscriptsJournal/ManuscriptsTab.lua:696: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@ManuscriptsJournal/ManuscriptsTab.lua"]:696: in function <ManuscriptsJournal/ManuscriptsTab.lua:695>
[string "@Blizzard_SharedXML/EventUtil.lua"]:74: in function <Blizzard_SharedXML/EventUtil.lua:66>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua"]:9: in function <...ns/Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua:8>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventoryClient.lua"]:935: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13471: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13494: in function `BlizzardAPIHook'
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
(*temporary) = nil
(*temporary) = "ManuscriptsJournal"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
addonName = "ManuscriptsJournal"
collectedManuscriptFilter = true
uncollectedManuscriptFilter = true
unusableManuscriptFilter = false
sourceFilter = <table> {
}

**Comment by fraerie** [comment]
Also:

1x ManuscriptsJournal/MOPRemixGemsTab.lua:921: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@ManuscriptsJournal/MOPRemixGemsTab.lua"]:921: in function <ManuscriptsJournal/MOPRemixGemsTab.lua:920>
[string "@Blizzard_SharedXML/EventUtil.lua"]:74: in function <Blizzard_SharedXML/EventUtil.lua:66>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua"]:9: in function <...ns/Blizzard_SharedXMLBase/GlobalCallbackRegistry.lua:8>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventoryClient.lua"]:935: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13471: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13494: in function `BlizzardAPIHook'
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
(*temporary) = nil
(*temporary) = "ManuscriptsJournal"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"
addonName = "ManuscriptsJournal"

**Comment by fraerie** [comment]
And more:

1x ManuscriptsJournal/enums.lua:143: attempt to call global 'GetSpellInfo' (a nil value)
[string "@ManuscriptsJournal/enums.lua"]:143: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventoryClient.lua"]:935: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13471: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13494: in function `BlizzardAPIHook'
[string "@ArkInventory/Core/ArkInventory.lua"]:3137: in function <ArkInventory/Core/ArkInventory.lua:3093>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
addonName = "ManuscriptsJournal"
addon = <table> {
 FilterDropDownSystem = <table> {
 }
 Enum = <table> {
 }
 Strings = <table> {
 }
 FilterComponent = <table> {
 }
}
L = <table> {
 Gorjo the Crab Shackler = "Gorjo the Crab Shackler"
 Lady Shaz'ra = "Lady Shaz'ra"
 Quest = "Quest"
 Shadowstalker Soul = "Shadowstalker Soul"
 Fisherman Tinnak = "Fisherman Tinnak"
 Fyrakk = "Fyrakk the Blazing"
 Valfir the Unrelenting = "Valfir the Unrelenting"
 Ixallon the Soulbreaker = "Ixallon the Soulbreaker"
 Goopal = "Goopal"
 TAB_TITLE = "Soulshapes"
 Otter Soul = "Otter Soul"
 Available since = "Available since"
 Renown = "Renown"
 Vendor = "Vendor"
 Dragonhunter Gorund = "Dragonhunter Gorund"
 Shrouded Cypher Cache Tooltip = "Activate Pocopoc's |T134442:0|t |cFFFFFFFFPerceptive Pocopoc|r buff while wearing a piece of Cypher Equipment with |cFFFFFFFFTreasurefinder|r to see the caches."
 Lost Comb = "Lost Comb"
 Lost Soul = "Lost Soul"
 Scorpid Soul = "Scorpid Soul"
 Cascade = "Cascade"
 Queen's Conservatory = "Queen's Conservatory"
 Wildseed Root Grain = "Wildseed Root Grain"
 Gamgus = "Gamgus"
 Tindral Sageswift = "Tindral Sageswift, Seer of the Flame"
 Snufflegust = "Snufflegust"
 Spellforged Brute = "Spellforged Brute"
 Olea Manu = "Olea Manu"
 Stygian Lockbox = "Stygian Lockbox"
 Ty'foon the Ascended = "Ty'foon the Ascended"
 The Power of Elune = "The Power of Elune"
 Honmor = "Honmor"
 Trilvarus Loreweaver = "Trilvarus Loreweaver"
 Treasure-Mad Trambladd = "Treasure-Mad Trambladd"
 So'leah = "So'leah"
 Secured Shipment = "Secured Shipment"
 Bisquius = "Bisquius"
 Hippogryph Soul = "Hippogryph Soul"
 The Grand Menagerie = "The Grand Menagerie"
 Battlehorn Pyrhus = "Battlehorn Pyrhus"
 Ookbeard = "Ookbeard"
 Forgotten Dragon Treasure = "Forgotten Dragon Treasure"
 NPC = "NPC"
 Warlord Sargha = "Warlord Sargha"
 Firava the Rekindler = "Firava the Rekindler"
 Aurostor, the Hibernating = "Aurostor, The Hibernator"
 Qalashi War Mammoth = "Qalashi War Mammoth"
 Loot = "Loot"
 Beogoka = "Beogoka"
 Dragon Racing Container = "Dragon Racing Containers"
 Hippo Soul Guide = "Reward from Night Fae Assault."
 Alcanon = "Alcanon"
 Jormungar Soul = "Jormungar Soul"
 Penguin Soul = "Penguin Soul"
 Invoq = "Invoq"
 High Shaman Rotknuckle = "High Shaman Rotknuckle"
 Queen's Conservatory Cache = "Queen's Conservatory Cache"
 COUNT_LABEL = "Total"
 Gigi Gigavoid = "Gigi Gigavoid"
 Graniteclaw = "Graniteclaw"
 Soulshape = "Soulshape"
 Sparkle = "Sparkle"
 Turkey Soul Guide = "Go to a faction capital, and find a Pilgrim’s Bounty table.
Eat every food until you have the 5 food buffs, then continue eating food and switching seats every time until you get the soulshape."
 Taskmaster Xy'pro Tooltip = "Drops |T465877:0|t |cff14b200Security Override Orb|r when killed with the |T465877:0|t |cFFFFFFFFSecurity Override|r buff.|n|nFor every additional mob around him, Xy'pro gets a stack of |T135740:0|t |cFFFFFFFFSynergy|r. At 3 stacks he gets |T465877:0|t |cFFFFFFFFSecurity Override|r."
 The Adamant Vaults = "The Adamant Vaults"
 Cortinarius = "Cortinarius"
 Echo of Doragosa = "Echo of Doragosa"
 Azra's Prized Peony = "Azra's Prized Peony"
 Brutosaur Soul = "Brutosaur Soul"
 Summoned Destroyer = "Summoned Destroyer"
 Zenet Avis = "Zenet Avis"
 Waterlogged Bundle = "Waterlogged Bundle"
 Saurolisk Soul = "Saurolisk Soul"
 O'nank Shorescour = "O'nank Shorescour"
 Maximum = "Maximum"
 Viridian King = "Viridian King"
 War Chest of the Wild Hunt = "War Chest of the Wild Hunt"
 Warlords of Draenor Timewalking = "Warlords of Draenor Timewalking"
 Razk'vex the Untamed = "Razk'vex the Untamed"
 Equine Soul = "Equine Soul"
 Gryphon Soul = "Gryphon Soul"
 Seeker Teryx = "Seeker Teryx"
 Gushgut the Beaksinker = "Gushgut the Beaksinker"
 Required Rank: = "Required Rank:"
 Rare Spawns = "Rare Spawns"
 Smelly Trash Pile = "Smelly Trash Pile"
 Tallstrider Soul = "Tallstrider Soul"
 Smogswog the Firebreather = "Smogswog the Firebreather"
 Chicken Soul Guide = "First get the Spectral Feed, then /chicken at the chicken soul and feed it the Spectral Feed."
 Grand Artificer Zeera

**Comment by teelolws** [comment]
Patch today broke most of my addons. I'll get to them tonight.
