### ISSUE TITLE
Request for additional Druid shapeshift forms

### ISSUE THREAD

**Issue by Hayleqwyn** [TLDRMissions/ManuscriptsJournal#49]
I was hoping you could add tracking for the Lunarwing flight form, the Druid of the Flame cat form, and the Blight of the Grizzlemaw bear form for Druids!

**Comment by teelolws** [comment]
I can add the Lunarwing one, tied to the quest that awards it.

Unless theres some new way to permanently learn the Druid of the Flame cat form, it doesn't fit here. Majordomos Seed Satchel is already tracked in the toy journal.

Grizzlemaw doesn't fit either as it requires wearing the artifact weapon, no?

**Comment by Hayleqwyn** [comment]
I've attached screenshots from https://www.wowhead.com/guide/druid-forms-customization-color-options with the info copy the other two forms. They both can be unlocked permanently at the barbershop.

![Screenshot_20241217_144849_Chrome](https://github.com/user-attachments/assets/7bde00e8-bea3-4561-8c3a-68ca6e0f27c8)
![Screenshot_20241217_145045_Chrome](https://github.com/user-attachments/assets/b312c740-a855-409f-a3f8-1ac836fb326a)
