### ISSUE TITLE
Overhaul druid customisations

### ISSUE THREAD

**Issue by teelolws** [TLDRMissions/ManuscriptsJournal#50]
Find a way to get completion status from the barber UI. Theres a lot of options and I don't have Quest IDs for them all.

**Comment by Hayleqwyn** [comment]
Most of the options that you are missing are likely the forms which are tied to the Legion Artifact weapons. Assuming this *is* the case, you would simply need to check whether that particularly artifact weapon appearance has been unlocked. For more information, I would check the following guides:
- https://www.wowhead.com/guide/druid-forms-customization-color-options
- https://www.wowhead.com/guide/legion-artifact-weapons#artifact-appearances-druid
- https://www.wowhead.com/guide/unlocking-artifact-appearances

If you would like any further help with specific forms, I'm happy to assist. I have experience with scripts for checking completion of various things in WoW, as well as writing code for addons. Just let me know which specific forms you need help with!

**Comment by teelolws** [comment]
A work in progress, heres what I have so far: 
![image](https://github.com/user-attachments/assets/697c8eeb-8adb-484e-b217-27a1804a4523)

**Comment by Hayleqwyn** [comment]
That's looking pretty good so far! And I'm glad to see it looks like you're separating the shapeshifts by form now (bear, cat, etc.) — I meant to suggest that, as it should make it much easier to look through!

**Comment by teelolws** [comment]
Okay done. I've done some sweeping changes to cut down on bloat in the codebase, so theres probably going to be a bug I missed somewhere.
