### ISSUE TITLE
Druid Tab Suggestions and Corrections

### ISSUE THREAD

**Issue by Hayleqwyn** [TLDRMissions/ManuscriptsJournal#51]
First, I noticed some weird glitches happening with the icons for the Legion artifact appearances, where they will get overridden by other icons if you flip between pages. I'm guessing this is because they have blank icons otherwise. My suggestion to fix this would be to use the icon for the appropriate Legion artifact weapon.

Second, while I think it's great to include the _Fandral's Seed Pouch_ toy that drops of Majordomo Staghelm, the fire cat form at the barbershop is actually unlocked when you collect the [Fandral's Flamescythe](https://www.wowhead.com/item=69897/fandrals-flamescythe) weapon for your transmog collection, so that should also be included.

**Comment by teelolws** [comment]
For the Firecat form: I needed an icon for it, and decided to go with the toy. It really doesn't matter what the item displayed is. The known/unknown status is learned from visiting the barber and checking your cat forms.

**Comment by Hayleqwyn** [comment]
> For the Firecat form: I needed an icon for it, and decided to go with the toy. It really doesn't matter what the item displayed is. The known/unknown status is learned from visiting the barber and checking your cat forms.

Except I've already learned the Firecat form from the staff but I don't have the toy, and it's not showing the form as learned in the addon. See screenshots.
![image](https://github.com/user-attachments/assets/d63bf220-da37-425e-af2c-22d7e2e4a1c2)
![image](https://github.com/user-attachments/assets/ee51117c-fd81-42fa-a483-de62fd0bff16)

**Comment by teelolws** [comment]
I dunno, works for me:
![image](https://github.com/user-attachments/assets/62d06b80-89c6-4255-bbe0-514a25df8ad1)

**Comment by Hayleqwyn** [comment]
But have you learned the toy?
