### ISSUE TITLE
Incorrect Druid Form ID

### ISSUE THREAD

**Issue by Hayleqwyn** [TLDRMissions/ManuscriptsJournal#52]
I found an error with one of the Druid form IDs. The final ID under Nature's Fury is a duplicate of one of the Incarnation of Nightmare forms. The correct ID should be 438.
![image](https://github.com/user-attachments/assets/962a8438-54b8-4c4f-b515-74e6bbedc8c1)
![image](https://github.com/user-attachments/assets/30ec252a-b160-4c5c-a96f-3e26e8c043ab)

**Comment by teelolws** [comment]
I see you fixed it on the page I got those IDs from: https://warcraft.wiki.gg/index.php?title=ArtifactAppearanceID&diff=6202635&oldid=4362810

**Comment by Hayleqwyn** [comment]
Lol, yes, I fixed that page as I realized it was also wrong there and that you probably got it from that page. =P
