### ISSUE TITLE
Fire cat form issue still present

### ISSUE THREAD

**Issue by Hayleqwyn** [TLDRMissions/ManuscriptsJournal#53]
I am still having the issue with the fire cat form, even after the most recent update. I managed to implement a workaround however that is working. Note that the implementation of transmogID2 is because the heroic version of the staff has a different appearance (purple color scheme instead of orange) and allows the addon to correctly mark the barbershop's fire cat appearance as learned even if only one of the staff's appearances has been collected. Additionally, I have set it so that the toy specifically tracks whether you know the toy or not, independent of having the fire cat appearance unlocked for the barbershop, because the toy has the advantage of allowing you to set a different cat appearance at the barbershop as your default appearance but then activate the fire cat appearance freely when out and about, so it seems handy to have people see it as a separate unlock.

The first screenshot's edit is to ShapeshiftsTab.lua. Added code for easier copy/paste:

```
	if data.toyID then
		return PlayerHasToy(data.toyID)
	end
	
	if data.transmogID then
		if data.transmogID2 then
			return C_TransmogCollection.PlayerHasTransmog(data.transmogID) or C_TransmogCollection.PlayerHasTransmog(data.transmogID2)
		else
			return C_TransmogCollection.PlayerHasTransmog(data.transmogID)
		end
	end
```

The second screenshot's edit is to db\Shapeshifts.lua. Added code for easier copy paste:

```
	-- 26 Druid of the Flame
	{
		itemID = 69897,
		name = "Fandral's Flamescythe",
        	-- customizationID = 15379,
		transmogID = 69897,
		transmogID2 = 71466,
		category = shapeshifts.Cat,
	},
	{
		itemID = 122304,
		name = "Fandral's Seed Pouch",
        	-- customizationID = 15379,
		toyID = 122304,
		category = shapeshifts.Cat,
	},
```
![image](https://github.com/user-attachments/assets/15230c87-08f2-457b-b01a-396c75b255c0)
![image](https://github.com/user-attachments/assets/bce26b4a-832d-4505-9768-e8b79ee55eec)

**Comment by teelolws** [comment]
What customization ID are you getting when setting the firecat form via the barber?

https://warcraft.wiki.gg/wiki/API_C_BarberShop.PreviewCustomizationChoice

`/run hooksecurefunc(C_BarberShop, "PreviewCustomizationChoice", function(...) print(...) end)`

![image](https://github.com/user-attachments/assets/f5b832c8-6545-45ed-a737-ebf7e7c9fbda)

**Comment by teelolws** [comment]
I was wondering if 15379 was possibly account locked but this rules that out: https://wago.tools/db2/ChrCustomizationChoice?sort[ID]=asc&filter[ID]=15379&page=1

Make sure the addon is registering your barber shop collection properly. Open the collections UI first so the addon loads in. Then visit the barber, pick cat form, and open the full customizations menu. Now when you go back to the manuscripts UI the fire cat should be marked as learned.

**Comment by Hayleqwyn** [comment]
It worked this time. I don't know why it didn't work before, as I did the exact same thing... o_O I still like having the toy listed separately from the actual barbershop check, so I'll keep my edit on my end, but at least I can now confirm your code _IS_ working.

**Comment by teelolws** [comment]
Compromise: how about I recreate this Classic-SOD item in the addon, and mark it based on the toy or weapon appearance as you did? https://www.wowhead.com/classic/item=232373/refined-eye-of-sulfuras#comments

**Comment by Hayleqwyn** [comment]
That's totally up to you. I can certainly keep copying my little bit of added code over whenever there's updates, like I do for several other addons. I just think listing the staff makes it clearer what is unlocking the appearance at the barbershop. But again, totally your call!

**Comment by teelolws** [comment]
I don't want to clutter up the addon with two buttons for the same appearance, so I'm landing on this:
![image](https://github.com/user-attachments/assets/bc5703fd-9c19-49cd-953a-bd189929eab2)


I don't have the toy so its red. I have the weapon appearance so its green.

**Comment by teelolws** [comment]
![image](https://github.com/user-attachments/assets/48ac8d13-c6f9-4e0b-8b9a-8f0fa2197ee7)
(fixed the isCollected)

**Comment by Hayleqwyn** [comment]
That's a perfect compromise! (Sorry for the super late response, life got crazy busy the past month or so.)
