### ISSUE TITLE
Suggestion: Keyboard shortcut

### ISSUE THREAD

**Issue by Arxareon** [TLDRMissions/ManuscriptsJournal#6]
Hey!

Lovely work! I'd love it there we had the ability to assign a keyboard shortcut to open and close the Manuscripts window. It's a small thing but if you ever find the time for it in the future, it could be a nice little addition. 😁

Cheers!

**Comment by teelolws** [comment]
The keybinding you have for Collections works - it just opens to whatever tab you already had open!

**Comment by Arxareon** [comment]
I have separate keys for each default tab. I didn't actually notice opening the window as a whole (not a specific tab in it) opens the last open tab but that's probably because I open specific tabs with different keys.
I think there'd still be use for it (if low priority) but if I have to open and close Manuscripts often when I'm browsing, this info should be useful! Thanks!

**Comment by teelolws** [comment]
Okay.

![image](https://user-images.githubusercontent.com/49792789/235325467-ea18e3dc-e2e7-473a-ab82-9f84acd8ce28.png)

Its not going to work if you're in combat - opening the Collections UI involves first opening the Mounts tab, and an addon cannot do that while you're in combat as it creates clickable action buttons on the screen, and only Blizzard code can do that. You can still open it via the menu button.
